In [1]:
!pip list

Package                       Version
----------------------------- ------------
absl-py                       2.1.0
aiofiles                      22.1.0
aiosqlite                     0.19.0
alembic                       1.12.1
altair                        5.1.2
anyio                         4.0.0
archspec                      0.2.1
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
arrow                         1.3.0
asttokens                     2.4.1
astunparse                    1.6.3
async-generator               1.10
async-lru                     2.0.4
attrs                         23.1.0
Babel                         2.13.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.5
beautifulsoup4                4.12.2
bleach                        6.1.0
blinker                       1.6.3
bokeh                         3.3.0
boltons                       23.0.0
Bottleneck                    1.3.7
Brotli                        1.1.0
cached-prop

In [2]:
import torch

In [20]:
my_torch = torch.arange(15)

In [21]:
my_torch = my_torch.view(-1,3)

In [22]:
my_torch

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [23]:
my_torch[:,1]

tensor([ 1,  4,  7, 10, 13])

tensor([[  0,   1,   4],
        [  9,  16,  25],
        [ 36,  49,  64],
        [ 81, 100, 121],
        [144, 169, 196]])