In [2]:
!pip list

Package            Version
------------------ -----------
accelerate         0.28.0
aiohttp            3.9.3
aiosignal          1.3.1
appnope            0.1.4
asttokens          2.4.1
attrs              23.2.0
beautifulsoup4     4.12.3
blinker            1.8.2
certifi            2024.2.2
charset-normalizer 3.3.2
click              8.1.7
comm               0.2.2
contourpy          1.2.1
cycler             0.12.1
datasets           2.18.0
debugpy            1.8.1
decorator          5.1.1
dill               0.3.8
dnspython          2.6.1
evaluate           0.4.1
executing          2.0.1
filelock           3.13.1
Flask              3.0.3
Flask-Cors         4.0.1
Flask-Login        0.6.3
Flask-SQLAlchemy   3.1.1
Flask-WTF          1.2.1
fonttools          4.53.0
frozenlist         1.4.1
fsspec             2024.2.0
huggingface-hub    0.21.4
idna               3.6
ipykernel          6.29.3
ipython            8.22.2
itsdangerous       2.2.0
jedi               0.19.1
Jinja2             3.1.3
jo

In [3]:
import torch

In [4]:
my_torch = torch.arange(15)

In [5]:
my_torch = my_torch.view(-1,3)

In [6]:
my_torch

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [7]:
my_torch[:,1]

tensor([ 1,  4,  7, 10, 13])

In [9]:
my_torch

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [10]:
torch.cuda.is_available()

False

In [11]:
torch.mul(my_torch, my_torch)

tensor([[  0,   1,   4],
        [  9,  16,  25],
        [ 36,  49,  64],
        [ 81, 100, 121],
        [144, 169, 196]])

In [12]:
my_torch.add(my_torch)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16],
        [18, 20, 22],
        [24, 26, 28]])

In [13]:
my_torch_1 = torch.arange(15)

In [17]:
my_torch_1 = my_torch_1.view(-1,3)

In [18]:
my_torch_1

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [19]:
my_torch_1.add_(my_torch_1)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16],
        [18, 20, 22],
        [24, 26, 28]])

In [21]:
my_torch_1.add_(my_torch)

tensor([[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24],
        [27, 30, 33],
        [36, 39, 42]])

In [22]:
my_torch

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])